### ISSUE TITLE
ConvertToString<T> issue

### ISSUE THREAD

**Issue by aorgish** [romaGri/.NET-Tasks#1]
https://github.com/romaGri/.NET-Tasks/blob/a6846a89029245dbb58040098adf2e84791827e9/02-Generics/Generics/Generics.cs#L37

А зачем тут ToArray() ?

**Comment by romaGri** [comment]
Руководствовался этим:
Join(String, Object[])  Concatenates the elements of an object array, using the specified separator between each element.
